version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - GITHUB_HOST=${GITHUB_HOST:-https://api.github.com}
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-mistral}
    depends_on:
      - ollama
    networks:
      - nomorereports-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - nomorereports-network

volumes:
  ollama-data:

networks:
  nomorereports-network:
    driver: bridge 