server:
  port: 8080
  servlet:
    async:
      request-timeout: 600000
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 600000

spring:
  application:
    name: nomorereports
  webflux:
    base-path: /
  mvc:
    async:
      request-timeout: 600000

app:
  github:
    default-host: https://api.github.com
    default-token: ${GITHUB_TOKEN:}
  ollama:
    base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
    model: ${OLLAMA_MODEL:tinyllama}

logging:
  level:
    com.njhyuk.nomoreports: DEBUG
    org.springframework.web.reactive.function.client: DEBUG 